services:
  prometheus:
    image: ${NEXUS_URL}/prom/prometheus:${PROM_TAG}
    networks:
      - prometheus
      - traefik-net
    volumes:
      - prometheus:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    user: "root"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.prom.entrypoints=http"
        - "traefik.http.routers.prom.rule=Host(`${PROM_DOMAIN}.${DOMAIN}`)"
        - "traefik.http.middlewares.prom-auth.basicauth.users=${PROM_AUTH_USER}:${PROM_AUTH_PASS}"
        - "traefik.http.routers.prom.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.prom-secure.entrypoints=https"
        - "traefik.http.routers.prom-secure.rule=Host(`${PROM_DOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.prom-secure.tls=true"
        - "traefik.http.routers.prom-secure.middlewares=prom-auth"
        - "traefik.http.routers.prom-secure.tls.certresolver=mycert"
        - "traefik.http.services.prom.loadbalancer.server.port=9090"

  grafana:
    image: ${NEXUS_URL}/grafana/grafana:${GRAFANA_TAG}
    networks:
      - traefik-net
      - prometheus
    volumes:
      - grafana:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN}.${DOMAIN}
    secrets:
      - grafana_admin_password
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-net"
        - "traefik.http.routers.grafana.entrypoints=http"
        - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.grafana.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.grafana-secure.entrypoints=https"
        - "traefik.http.routers.grafana-secure.rule=Host(`${GRAFANA_DOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.grafana-secure.tls=true"
        - "traefik.http.routers.grafana-secure.tls.certresolver=mycert"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  node_exporter:       
    image: ${NEXUS_URL}/bitnami/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      mode: global
    networks:
      - prometheus

networks:
  traefik-net:
    external: true
  prometheus:
    external: true

volumes:
  prometheus:
    external: true
  grafana:
    external: true

secrets:
  grafana_admin_password:
    external: true
