global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    monitor: prom

rule_files:
  - /etc/prometheus/alerts/*.rules

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance

  - job_name: 'traefik'
    static_configs:
    - targets: ['traefik:8082']

  - job_name: 'grafana'
    static_configs:
    - targets: ['grafana:3000']

  - job_name: 'node'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: 'prometheus_stack_node_exporter'
        action: keep
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: 'running'
        action: keep
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):(.*)'
        replacement: '$1:9100'

  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkwNzg5NTF9.v3QlwSXomQpVko_iYpD3Be1s1FsnigPVtxDYPRxxJ_7vmVSeXAtu25vKC1Y8w1lPIt0vD2M_gXpFPZqFWkGroA
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['miniop:9000']
  - job_name: minio-job-node
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkwODA0ODd9.pE_x8qSYsgURboU0lzBN_lW1UKNqH8OGeRn98wP3Mte65iMIAac7OW2tnyF8mzKhHSGYSQZg7qu0BaN7jcnsrw
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
    - targets: 
      - 'minio-1:9000'
      - 'minio-2:9000'
      - 'minio-3:9000'
  - job_name: minio-job-bucket
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkwODA2Mjh9.2mnsS_-oihQSFjZyctkeiD7qG97pK43PTQcQ0NoYWkNywzTz3ituZe-UZSryT2CTJm7JkFGl3GNCO8kPoUkfFQ
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
    - targets: ['miniop:9000']
  - job_name: minio-job-resource
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiYWRtaW4iLCJleHAiOjQ4NzkwODA2ODJ9.oGwTbp9pve6eZc1N7zpQnV077Mn0valMol7_thBFaZ2kZsf7li0QbM9OVwQKzP2c0KkjyAoLy8g2EzEQicvS3Q
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
    - targets: ['miniop:9000']