---
- name: Deploy Docker Stacks on Docker Swarm
  hosts: tavana-swarm2
  become: true
  vars:
    services:
      - traefik
      - monlog
      - minio
  tasks:
    #   - name: Install dependencies to load compose file.
    #    ansible.builtin.apt:
    #      name:
    #        - python3-jsondiff
    #        - python3-yaml
    #      state: present

    - name: Load environment variables for each service
      ansible.builtin.include_vars:
        file: ../{{ item }}/{{ item }}.env
        name: "{{ item }}_vars"
      loop: "{{ services }}"

    - name: Copy service compose files to /opt directory
      ansible.builtin.copy:
        src: ../{{ item }}/{{ item }}.yml
        dest: /opt
        mode: "0600"
      loop: "{{ services }}"

    - name: Ensure the Docker networks exist
      community.docker.docker_network:
        name: "{{ item }}"
        driver: overlay
        attachable: true
        state: present
      loop:
        - traefik-net
        - prometheus
        - minio

    - name: Deploy Docker Stacks using compose files
      community.docker.docker_stack:
        name: "{{ item }}"
        compose:
          - /opt/{{ item }}.yml
      environment: "{{ lookup('vars', item + '_vars') }}"
      loop: "{{ services }}"
