---
- name: Docker volumes and its contents.
  hosts: swarm
  become: true
  tasks:
    - name: Create docker volume
      community.docker.docker_volume:
        volume_name: "{{ item }}"
        state: present
        driver: local
      loop:
        - traefik-acme
        - prometheus
        - grafana
        - minio-policies
        - mimir

    - name: Copy volume content
      ansible.builtin.copy:
        dest: /var/lib/docker/volumes/{{ item.dst }}/_data/
        src: "{{ item.src }}"
      loop:
        - { src: ../traefik/tls.yml, dst: traefik-acme }
        - { src: ../traefik/domain.key, dst: traefik-acme }
        - { src: ../traefik/domain.cert, dst: traefik-acme }
        - { src: ../monlog/prometheus.yml, dst: prometheus }
        - { src: ../monlog/alerts/, dst: prometheus }
        - { src: ../monlog/grafana/, dst: grafana }
        - { src: ../monlog/mimir.yml, dst: mimir }
        - { src: ../minio/policies/, dst: minio-policies }
