---
- name: Pull docker images
  hosts: swarm
  become: true
  tasks:
    - name: Check if image exists
      community.docker.docker_image_pull:
        name: docker.tavana.local/{{ item }}
      loop:
        - traefik:v3.1
        - prom/prometheus:v2.54.1
        - grafana/grafana:11.2.0
        - bitnami/node-exporter
        - minio/minio:RELEASE.2024-08-29T01-40-52Z
