---
- name: Deploy Docker Stacks on Docker Swarm
  hosts: swarm
  tasks:
    - name: Ensure the Docker networks exist
      community.docker.docker_network:
        name: "{{ item }}"
        driver: overlay
        attachable: true
        state: present
      loop:
        - traefik-net
        - prometheus

    - name: Set environment variables
      ansible.builtin.set_fact:
        DOMAIN: tavana.local
        NEXUS_URL: docker.{{ DOMAIN }}

    - name: Include environment variables from traefik.env
      ansible.builtin.include_vars:
        file: traefik/traefik.env

    - name: Deploy Traefik stack
      ansible.builtin.command: docker stack deploy -c traefik/traefik.yml --detach=true traefik
      environment:
        DOMAIN: "{{ DOMAIN }}"
        NEXUS_URL: "{{ NEXUS_URL }}"
      become: true

    - name: Include environment variables from monlog.env
      ansible.builtin.include_vars:
        file: monlog/monlog.env

    - name: Deploy Prometheus stack
      ansible.builtin.command: docker stack deploy -c monlog/monlog.yml --detach=true prometheus_stack
      environment:
        DOMAIN: "{{ DOMAIN }}"
        NEXUS_URL: "{{ NEXUS_URL }}"
      become: true
