---
- name: cionfigure names
- hosts: swarm
  gather_facts: false
  tasks:
    - name: Add line to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      become: true
      loop:
        - 192.168.1.4     docker.tavana.local
