{
 "title": "Prometheus Metrics Overview",
 "description": "Inspect the cardinality of your metrics ",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "metric", "query": { "query": "label_values(__name__)" } },
   { "name": "job", "label": "job (filter for metrics)", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Total series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  },
  {
   "title": "Total metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count({__name__!=\"\"}) by (__name__))"
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count({__name__!=\"\"}) by (job))"
    }
   ]
  },
  {
   "title": "Cardinality by label for selected metric",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 0, "y": 4 },
   "targets": [
    { "expr": "$metric" }
   ]
  },
  {
   "title": "Series by metric (top 100)",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "topk(100, count({__name__!=\"\",job=~\"$job\"}) by (__name__))"
    },
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  },
  {
   "title": "Series by job (top 100)",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "topk(100, count({__name__!=\"\"}) by (job))"
    },
    {
     "expr": "count({__name__!=\"\"})"
    }
   ]
  }
 ]
}