{
 "title": "Docker Swarm Overview",
 "description": "This dashboard provides general information about the status of the swarm cluster. Prometheus is used as a source. Metrics should be collected using docker native exporter.\r\nTo enable docker native exporter, add the following parameter to the daemon.json config:\r\n{\r\n    \"metrics-addr\": \"0.0.0.0:9323\"\r\n}",
 "tags": [
  "docker swarm",
  "docker-exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "leader",
    "label": "Swarm Leader",
    "query": {
     "query": "query_result(max(swarm_manager_leader ==1) by (instance))"
    }
   },
   {
    "name": "cluster",
    "label": "Swarm СlusterID",
    "query": {
     "query": "label_values(swarm_node_info,swarm_id)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(swarm_node_info{swarm_id=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "leader" },
  {
   "title": "Swarm Manager Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_nodes{instance=~\"$leader\",state=\"ready\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "swarm_manager_nodes{instance=~\"$leader\",state=\"down\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "swarm_manager_nodes{instance=~\"$leader\",state=\"disconnected\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "swarm_manager_nodes{instance=~\"$leader\",state=\"unknown\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Swarm Manager Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "max(swarm_manager_leader) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers (running)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_tasks_total{instance=~\"$leader\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Cluster Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_services_total{instance=~\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Secrets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_secrets_total{instance=~\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Configs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_configs_total{instance=~\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Networks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swarm_manager_networks_total{instance=~\"$leader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Node info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "collapsed": true
  },
  {
   "title": "Swarm Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "swarm_node_info{swarm_id=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swarm Nodes Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "engine_daemon_engine_info{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}