{
 "title": "DataCore Swarm Node View",
 "description": "Swarm dashboard to see servers running node_exporter service, contains enhanced panels for swarm software as well.",
 "tags": [ "public" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "2m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(node_exporter_build_info{env='$env'},name)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_exporter_build_info{name='$name'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU avg（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100"
    }
   ]
  },
  {
   "title": "fd allocated",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "node" },
  {
   "title": "load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\"}[$interval]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "CPU Core Utilization for Date Range",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\"}[$interval]),1)) )),1)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=~\"$node\",mode!=\"idle\"}[$interval]),1)) )),1)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU load over time（%）",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_I/O%"
    }
   ]
  },
  {
   "title": "disk io",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "disk r/w bytes",
   "type": "timeseries",
   "description": "Read bytes\nWritten bytes",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_write"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'$node'}[$interval])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'$node'}[$interval])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'$node'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  {
   "title": "Net IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$node',device!~'tap.*'}[$interval])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$node',device!~'tap.*'}[$interval])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "Context Switches vs interrupts (rate $interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"$node\"}[$interval])",
     "legendFormat": "context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=\"$node\"}[$interval])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_processes_pids", "legendFormat": "{{instance}}" },
    { "expr": "node_netstat_Tcp_CurrEstab", "legendFormat": "TCP {{instance}}" }
   ]
  },
  {
   "title": "UDP InErrors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "node_netstat_Udp_InErrors{instance=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP / Multicast traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(node_netstat_Udp_InDatagrams{instance='$node'}[1h]))",
     "legendFormat": "Inbound UDP traffic"
    },
    {
     "expr": "sum(rate(node_netstat_Udp_OutDatagrams{instance='$node'}[1h]))",
     "legendFormat": "outbound UDP traffic"
    },
    {
     "expr": "sum(rate(node_network_receive_multicast_total{instance='$node'}[1h]))",
     "legendFormat": "multicast traffic"
    }
   ]
  },
  {
   "title": "Disk usage % ( Not applicable for Swarm Storage )",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{instance=\"$node\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=\"$node\",fstype=~\"xfs|ext4\"})",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Swarm Specific Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "UDP Send/RecvBufErrors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "node_netstat_Udp_RcvbufErrors{instance='$node'}",
     "legendFormat": "{{instance}} RXERRS"
    },
    {
     "expr": "node_netstat_Udp_SndbufErrors{instance='$node'}",
     "legendFormat": "{{instance}} TXERRS"
    }
   ]
  },
  {
   "title": "Node UDP Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum_over_time(node_udp_queues{ip='v4',queue='rx',instance='$node'}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UDP Connections Attempts rate(24h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "rate(caringo_swarm_udp_connection_attempts{instance=~'$node'}[1h])",
     "legendFormat": "TO: {{ip_address}}"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$node'}",
     "legendFormat": "{{chip}}/{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU Scaling Frequency (Hertz)",
   "type": "timeseries",
   "description": "If you see \"No Data\" it means cpu scaling is not enabled in the BIOS. Check the bios performance workload profile.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max(node_cpu_scaling_frequency_max_hertz{instance=~'$node'}) by (instance)",
     "legendFormat": "{{instance}}-MAX Freq"
    },
    {
     "expr": "min(node_cpu_scaling_frequency_min_hertz{instance=~'$node'}) by (instance)",
     "legendFormat": "{{instance}} - MIN Freq"
    },
    {
     "expr": "max(node_cpu_scaling_frequency_hertz{instance=~'$node'}) by (instance)",
     "legendFormat": "{{instance}}-max Scaling"
    },
    {
     "expr": "min(node_cpu_scaling_frequency_hertz{instance=~'$node'}) by (instance)",
     "legendFormat": "{{instance}}-min Scaling"
    }
   ]
  },
  {
   "title": "CPU Throttles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_package_throttles_total{instance=~'$node'}[1h])) by (package,core)",
     "legendFormat": "P{{package}}"
    },
    {
     "expr": "rate(node_cpu_core_throttles_total{instance=~'$node'}[1h])",
     "legendFormat": "P{{package}}/C{{core}}"
    }
   ]
  }
 ]
}